CREATE TABLE [dbo].[Contacts](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[UserId] [NVARCHAR](450) NOT NULL,
	[Name] [NVARCHAR](50) NOT NULL,
	[Address] [NVARCHAR](50) NULL,
	[Email] [NVARCHAR](50) NULL,
 CONSTRAINT [PK_Contacts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
