//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 11/30/2020 12:13:08 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Contacts.Data.Contacts
{
    public partial class Contact {

        public Contact()
        {
            OnCreated();
        }

        public virtual int Id { get; set; }

        public virtual string UserId { get; set; }

        public virtual string Name { get; set; }

        public virtual string Address { get; set; }

        public virtual string Email { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
